Shows other users
Tobi3010/DIS-Project pull request #26
Opened 2024-06-08 22:23 UTC by Zhadowseb

The intention is to build on Toby's idea of maybe showing other users, having a friendship list and stuff like that. For now it just shows a list of other users, where you to begin with could add a button like visited. I don't think however i feel like adding anymore, so this may just be the end of it.

2024-06-08 22:57 UTC, Tobi3010 requested changes
Den burde nok ikke vise brugernavnet på den bruger man er logget ind på.

2024-06-08 23:59 UTC, Zhadowseb commented
> Den burde nok ikke vise brugernavnet på den bruger man er logget ind på.

Tjaa, nej det er nok rigtigt nok, men igen vi tjekker heller ikke at brugeren bliver logget ordenligt ind, det handler vel mest om databasen. Kan godt ændre det hvis det virkelig går dig på, men vil egentligt bare gerne være færdig med projektet...

2024-06-09 00:23 UTC, Tobi3010 commented
> > Den burde nok ikke vise brugernavnet på den bruger man er logget ind på.
> 
> Tjaa, nej det er nok rigtigt nok, men igen vi tjekker heller ikke at brugeren bliver logget ordenligt ind, det handler vel mest om databasen. Kan godt ændre det hvis det virkelig går dig på, men vil egentligt bare gerne være færdig med projektet...

Det har noget med databasen at gøre, du skal lave en query som finder alle brugernavnene bortset fra den bruger man er logget ind på.
Og ikke for noget, men du kan ikke tillade dig at sige "vil bare gerne være færdig med projektet.." når du næsten ikke har bidraget. Og det er ikke en undskyldning at sige at mig og Mark havde lavet meget af det i forvejen, fordi vi ville ikke være færdig med projektet, hvis vi alle sammen først begyndte 3 dage før....

Nu er denne besked også på github, så lad os håbe de ikke kigger for meget ;)
(Jeg sletter beskeden før vi aflevere, så ond er jeg heller ikke lol)

2024-06-09 01:47 UTC, Zhadowseb commented
> > > Den burde nok ikke vise brugernavnet på den bruger man er logget ind på.
> > 
> > 
> > Tjaa, nej det er nok rigtigt nok, men igen vi tjekker heller ikke at brugeren bliver logget ordenligt ind, det handler vel mest om databasen. Kan godt ændre det hvis det virkelig går dig på, men vil egentligt bare gerne være færdig med projektet...
> 
> Det har noget med databasen at gøre, du skal lave en query som finder alle brugernavnene bortset fra den bruger man er logget ind på. Og ikke for noget, men du kan ikke tillade dig at sige "vil bare gerne være færdig med projektet.." når du næsten ikke har bidraget. Og det er ikke en undskyldning at sige at mig og Mark havde lavet meget af det i forvejen, fordi vi ville ikke være færdig med projektet, hvis vi alle sammen først begyndte 3 dage før....
> 
> Nu er denne besked også på github, så lad os håbe de ikke kigger for meget ;) (Jeg sletter beskeden før vi aflevere, så ond er jeg heller ikke lol)



> > > Den burde nok ikke vise brugernavnet på den bruger man er logget ind på.
> > 
> > 
> > Tjaa, nej det er nok rigtigt nok, men igen vi tjekker heller ikke at brugeren bliver logget ordenligt ind, det handler vel mest om databasen. Kan godt ændre det hvis det virkelig går dig på, men vil egentligt bare gerne være færdig med projektet...
> 
> Det har noget med databasen at gøre, du skal lave en query som finder alle brugernavnene bortset fra den bruger man er logget ind på. Og ikke for noget, men du kan ikke tillade dig at sige "vil bare gerne være færdig med projektet.." når du næsten ikke har bidraget. Og det er ikke en undskyldning at sige at mig og Mark havde lavet meget af det i forvejen, fordi vi ville ikke være færdig med projektet, hvis vi alle sammen først begyndte 3 dage før....
> 
> Nu er denne besked også på github, så lad os håbe de ikke kigger for meget ;) (Jeg sletter beskeden før vi aflevere, så ond er jeg heller ikke lol)

Ja det kan gøres med en query, og det er nok også bedst, den måde jeg havde i hovedet krævede var ikke gennem query.

Jeg vil absolut tillade mig at sige jeg "jeg bare gerne vil være færdig med projektet". Jeg giver dig ret i det ikke er særlig meget jeg har bidraget, men jeg har som nævnt døjet med sygdom, og har på ingen måde overskud til at lave extra hvis opgaven allerede lever op til kravene, jeg har hele studieforløbet haft holdningen at jeg blot vil leverer nok til at bestå, og ikke mere end det. Det er ikke engang en eksamen det her. Til info kan jeg hilse og sige dit første pr er fem dage før, så det er ikke fordi du selv har været ude flere uger før. Det er ikke meningen det her skal være et angreb tilbage igen, jeg sætter pris på at i har været forstående for min sygdom, men jeg synes ikke dine kommentarer her er passende.

2024-06-09 02:56 UTC, Tobi3010 approved these changes

2024-06-09 09:05 UTC, ploeh commented
> [...] vil egentligt bare gerne være færdig med projektet...

Jeg vil også gerne være færdig med projektet. Lad os overveje hvad der skal til.

En eller flere personer skal vurdere, om de kan godkende vores aflevering. Resultatet kan kun være enten _godkendt_ eller _ikke godkendt_.

Det bliver nok i vid udstrækning instruktorer, der skal foretage den vurdering, selv om det er muligt at professorerne også kommer til at kigge med. Baseret på den måde opgaven og kravene er formuleret, fornemmer jeg at opgaven med at rette projekterne vil blive distribueret blandt instruktorer, ligesom de øvrige afleveringer. For at sikre en fair og ensartet vurdering vil jeg yderlige formode, at instruktorer har fået besked på at fokusere på, om de 'hårde' krav er mødt.

Så vidt jeg kan se, er der 283 studerende tilmeldt kurset, så der er sandsynligvis omkring 100 projekter, der skal vurderes.

Den letteste, mest ensartede og mest retfærdige proces er nok at instruktorer og professorer foretager en grovsortering, sådan at alle de projekter, der indiskutabelt opfylder de formelle krav, bliver godkendt. Her er trods alt ikke tale om en eksamen, men blot tilladelse til at gå til eksamen.

Hvordan vil en instruktor sætte hakker ved vores projekt, som det præsenterer sig i nuværende form?

- [x] Use a git repository for the source code and documentation
- [x] Make sure that we (Panos and I) and your TA have read access
- [x] E.g., use https://git.ku.dk/ and give us and your TA access or use a public GitHub repository
- [ ] Your database model (E/R diagram)
- [x] How to compile your web-app from source (incl. scripts to initialize the database)?
- [x] How to run and interact with your web-app?
- [x] The web-app Should interact with the database via SQL (at least one INSERT/UPDATE/DELETE/SELECT statement)
- [x] [NEW] Should perform regular expression matching or context-free grammar parsing

Jeg tror ikke at vi kommer nærmere målet ved at skrive mere kode. Det punkt er allerede vinget af.

Det er ikke et formelt krav at alle gruppemedlemmer skal have bidraget lige meget. Hvis jeg var en instruktor der skulle se 20-30 opgaver igennem ville jeg koncentrere mig om ovenstående tjekliste, og overhovedet ikke kigge på, hvem der har lavet hvad.

Skulle man undlade at godkende et projekt fordi et ud af tre medlemmer måske ikke har skrevet en tredjedel af koden? Det ville jo gå ud over de to andre, som så heller ikke ville få lov til at gå til eksamen.

_Vi mangler E/R-diagrammet._ Det er det eneste vi mangler for at være færdige.

2024-06-09 09:29 UTC, Zhadowseb commented
> > > > > Den burde nok ikke vise brugernavnet på den bruger man er logget ind på.
> > > > 
> > > > 
> > > > Tjaa, nej det er nok rigtigt nok, men igen vi tjekker heller ikke at brugeren bliver logget ordenligt ind, det handler vel mest om databasen. Kan godt ændre det hvis det virkelig går dig på, men vil egentligt bare gerne være færdig med projektet...
> > > 
> > > 
> > > Det har noget med databasen at gøre, du skal lave en query som finder alle brugernavnene bortset fra den bruger man er logget ind på. Og ikke for noget, men du kan ikke tillade dig at sige "vil bare gerne være færdig med projektet.." når du næsten ikke har bidraget. Og det er ikke en undskyldning at sige at mig og Mark havde lavet meget af det i forvejen, fordi vi ville ikke være færdig med projektet, hvis vi alle sammen først begyndte 3 dage før....
> > > Nu er denne besked også på github, så lad os håbe de ikke kigger for meget ;) (Jeg sletter beskeden før vi aflevere, så ond er jeg heller ikke lol)
> > 
> > > > > Den burde nok ikke vise brugernavnet på den bruger man er logget ind på.
> > > > 
> > > > 
> > > > Tjaa, nej det er nok rigtigt nok, men igen vi tjekker heller ikke at brugeren bliver logget ordenligt ind, det handler vel mest om databasen. Kan godt ændre det hvis det virkelig går dig på, men vil egentligt bare gerne være færdig med projektet...
> > > 
> > > 
> > > Det har noget med databasen at gøre, du skal lave en query som finder alle brugernavnene bortset fra den bruger man er logget ind på. Og ikke for noget, men du kan ikke tillade dig at sige "vil bare gerne være færdig med projektet.." når du næsten ikke har bidraget. Og det er ikke en undskyldning at sige at mig og Mark havde lavet meget af det i forvejen, fordi vi ville ikke være færdig med projektet, hvis vi alle sammen først begyndte 3 dage før....
> > > Nu er denne besked også på github, så lad os håbe de ikke kigger for meget ;) (Jeg sletter beskeden før vi aflevere, så ond er jeg heller ikke lol)
> > 
> > Ja det kan gøres med en query, og det er nok også bedst, den måde jeg havde i hovedet krævede var ikke gennem query.
> > 
> > Jeg vil absolut tillade mig at sige jeg "jeg bare gerne vil være færdig med projektet". Jeg giver dig ret i det ikke er særlig meget jeg har bidraget, men jeg har som nævnt døjet med sygdom, og har på ingen måde overskud til at lave extra hvis opgaven allerede lever op til kravene, jeg har hele studieforløbet haft holdningen at jeg blot vil leverer nok til at bestå, og ikke mere end det. Det er ikke engang en eksamen det her. Til info kan jeg hilse og sige dit første pr er fem dage før, så det er ikke fordi du selv har været ude flere uger før. Det er ikke meningen det her skal være et angreb tilbage igen, jeg sætter pris på at i har været forstående for min sygdom, men jeg synes ikke dine kommentarer her er passende.
> 
> Det er helt fint, jeg har godkendt det nu. Hvis det er, kan jeg godt lave ER diagrammet, hvis du ikke har overskud til det?

Det er sødt af dig at tilbyde, men jeg laver det her om et par timer. Du der dog meget velkommen til at tjekke om det er rigtigt dog.

2024-06-09 09:32 UTC, Zhadowseb commented
> > [...] vil egentligt bare gerne være færdig med projektet...
> 
> Jeg vil også gerne være færdig med projektet. Lad os overveje hvad der skal til.
> 
> En eller flere personer skal vurdere, om de kan godkende vores aflevering. Resultatet kan kun være enten _godkendt_ eller _ikke godkendt_.
> 
> Det bliver nok i vid udstrækning instruktorer, der skal foretage den vurdering, selv om det er muligt at professorerne også kommer til at kigge med. Baseret på den måde opgaven og kravene er formuleret, fornemmer jeg at opgaven med at rette projekterne vil blive distribueret blandt instruktorer, ligesom de øvrige afleveringer. For at sikre en fair og ensartet vurdering vil jeg yderlige formode, at instruktorer har fået besked på at fokusere på, om de 'hårde' krav er mødt.
> 
> Så vidt jeg kan se, er der 283 studerende tilmeldt kurset, så der er sandsynligvis omkring 100 projekter, der skal vurderes.
> 
> Den letteste, mest ensartede og mest retfærdige proces er nok at instruktorer og professorer foretager en grovsortering, sådan at alle de projekter, der indiskutabelt opfylder de formelle krav, bliver godkendt. Her er trods alt ikke tale om en eksamen, men blot tilladelse til at gå til eksamen.
> 
> Hvordan vil en instruktor sætte hakker ved vores projekt, som det præsenterer sig i nuværende form?
> 
> - [x] Use a git repository for the source code and documentation
> - [x] Make sure that we (Panos and I) and your TA have read access
> - [x] E.g., use https://git.ku.dk/ and give us and your TA access or use a public GitHub repository
> - [ ] Your database model (E/R diagram)
> - [x] How to compile your web-app from source (incl. scripts to initialize the database)?
> - [x] How to run and interact with your web-app?
> - [x] The web-app Should interact with the database via SQL (at least one INSERT/UPDATE/DELETE/SELECT statement)
> - [x] [NEW] Should perform regular expression matching or context-free grammar parsing
> 
> Jeg tror ikke at vi kommer nærmere målet ved at skrive mere kode. Det punkt er allerede vinget af.
> 
> Det er ikke et formelt krav at alle gruppemedlemmer skal have bidraget lige meget. Hvis jeg var en instruktor der skulle se 20-30 opgaver igennem ville jeg koncentrere mig om ovenstående tjekliste, og overhovedet ikke kigge på, hvem der har lavet hvad.
> 
> Skulle man undlade at godkende et projekt fordi et ud af tre medlemmer måske ikke har skrevet en tredjedel af koden? Det ville jo gå ud over de to andre, som så heller ikke ville få lov til at gå til eksamen.
> 
> _Vi mangler E/R-diagrammet._ Det er det eneste vi mangler for at være færdige.

Jeg er helt enig med dig her Mark. Jeg kigger på det om et par timer.

2024-06-09 14:41 UTC, Tobi3010 approved these changes

2024-06-09 15:54 UTC, merged